apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: imagerepo-mirror-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: imagerepo-mirror-role
subjects:
- kind: ServiceAccount
  name: imagerepo-mirror
  namespace: imagerepo-mirror-system
