apiVersion: v1
kind: ServiceAccount
metadata:
  name: imagerepo-mirror
  namespace: imagerepo-mirror-system
  annotations:
    # Replace with the GCP service account that has Workload Identity binding.
    # iam.gke.io/gcp-service-account: imagerepo-mirror@<YOUR_PROJECT>.iam.gserviceaccount.com
