apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../manager
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: imagerepo-mirror
    spec:
      template:
        spec:
          serviceAccountName: imagerepo-mirror
